-- Location Data for Book Echo Context System
-- Generated from Wowhead zones data
-- DO NOT EDIT MANUALLY - regenerate with scripts/generate_location_data.py

local LocationData = {}
BookArchivist.LocationData = LocationData

-- Category mapping
LocationData.CATEGORY = {
  [0] = "Eastern Kingdoms",
  [1] = "Kalimdor",
  [2] = "Dungeon",
  [3] = "Raid",
  [8] = "Outland",
  [10] = "Northrend",
  [11] = "Cataclysm Zone",
  [13] = "Draenor",
  [14] = "Broken Isles",
  [15] = "Kul Tiras",
  [16] = "Zandalar",
  [17] = "Shadowlands",
  [18] = "Dragon Isles",
  [19] = "Khaz Algar",
}

-- Expansion mapping
LocationData.EXPANSION = {
  [0] = "Classic",
  [1] = "The Burning Crusade",
  [2] = "Wrath of the Lich King",
  [3] = "Cataclysm",
  [4] = "Mists of Pandaria",
  [5] = "Warlords of Draenor",
  [6] = "Legion",
  [7] = "Battle for Azeroth",
  [8] = "Shadowlands",
  [9] = "Dragonflight",
  [10] = "The War Within",
}

-- Location type helpers
function LocationData:IsDungeon(category)
  return category == 2
end

function LocationData:IsRaid(category)
  return category == 3
end

function LocationData:IsInstance(category)
  return category == 2 or category == 3
end

-- All locations by ID
LocationData.byId = {
  [1] = {
    name = "Dun Morogh",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [3] = {
    name = "Badlands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [8] = {
    name = "Swamp of Sorrows",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [10] = {
    name = "Duskwood",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [11] = {
    name = "Wetlands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [12] = {
    name = "Elwynn Forest",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [14] = {
    name = "Durotar",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [15] = {
    name = "Dustwallow Marsh",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [16] = {
    name = "Azshara",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [17] = {
    name = "Northern Barrens",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [25] = {
    name = "Blackrock Mountain",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [28] = {
    name = "Western Plaguelands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [33] = {
    name = "Northern Stranglethorn",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [36] = {
    name = "Alterac Mountains",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [38] = {
    name = "Loch Modan",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [40] = {
    name = "Westfall",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [41] = {
    name = "Deadwind Pass",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [44] = {
    name = "Redridge Mountains",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [45] = {
    name = "Arathi Highlands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [46] = {
    name = "Burning Steppes",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [47] = {
    name = "The Hinterlands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [51] = {
    name = "Searing Gorge",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [65] = {
    name = "Dragonblight",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [66] = {
    name = "Zul'Drak",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [67] = {
    name = "The Storm Peaks",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [85] = {
    name = "Tirisfal Glades",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [130] = {
    name = "Silverpine Forest",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [139] = {
    name = "Eastern Plaguelands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [141] = {
    name = "Teldrassil",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [148] = {
    name = "Darkshore",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [206] = {
    name = "Utgarde Keep",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [209] = {
    name = "Shadowfang Keep",
    category = 2,
    expansion = 0,
    instance = 5,
  },
  [210] = {
    name = "Icecrown",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [215] = {
    name = "Mulgore",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [267] = {
    name = "Hillsbrad Foothills",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [331] = {
    name = "Ashenvale",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [357] = {
    name = "Feralas",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [361] = {
    name = "Felwood",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [394] = {
    name = "Grizzly Hills",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [400] = {
    name = "Thousand Needles",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [405] = {
    name = "Desolace",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [406] = {
    name = "Stonetalon Mountains",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [440] = {
    name = "Tanaris",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [457] = {
    name = "The Veiled Sea",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [490] = {
    name = "Un'Goro Crater",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [491] = {
    name = "Razorfen Kraul",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [493] = {
    name = "Moonglade",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [495] = {
    name = "Howling Fjord",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [616] = {
    name = "Mount Hyjal",
    category = 1,
    expansion = 3,
    instance = 0,
  },
  [618] = {
    name = "Winterspring",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [717] = {
    name = "The Stockade",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [718] = {
    name = "Wailing Caverns",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [719] = {
    name = "Blackfathom Deeps",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [721] = {
    name = "Gnomeregan",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [722] = {
    name = "Razorfen Downs",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [796] = {
    name = "Scarlet Monastery",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [876] = {
    name = "GM Island",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [1176] = {
    name = "Zul'Farrak",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [1196] = {
    name = "Utgarde Pinnacle",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [1337] = {
    name = "Uldaman",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [1377] = {
    name = "Silithus",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [1477] = {
    name = "Sunken Temple",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [1497] = {
    name = "Undercity",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [1519] = {
    name = "Stormwind City",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [1537] = {
    name = "Ironforge",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [1581] = {
    name = "The Deadmines",
    category = 2,
    expansion = 0,
    instance = 5,
  },
  [1583] = {
    name = "Blackrock Spire",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [1584] = {
    name = "Blackrock Depths",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [1637] = {
    name = "Orgrimmar",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [1638] = {
    name = "Thunder Bluff",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [1657] = {
    name = "Darnassus",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [1977] = {
    name = "Zul'Gurub",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [2017] = {
    name = "Stratholme",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [2057] = {
    name = "Scholomance",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [2100] = {
    name = "Maraudon",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [2159] = {
    name = "Onyxia's Lair",
    category = 3,
    expansion = 2,
    instance = 7,
  },
  [2257] = {
    name = "Deeprun Tram",
    category = 0,
    expansion = 0,
    instance = 1,
  },
  [2366] = {
    name = "The Black Morass",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [2367] = {
    name = "Old Hillsbrad Foothills",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [2437] = {
    name = "Ragefire Chasm",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [2557] = {
    name = "Dire Maul",
    category = 2,
    expansion = 0,
    instance = 2,
  },
  [2677] = {
    name = "Blackwing Lair",
    category = 3,
    expansion = 0,
    instance = 3,
  },
  [2717] = {
    name = "Molten Core",
    category = 3,
    expansion = 0,
    instance = 3,
  },
  [2817] = {
    name = "Crystalsong Forest",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [3428] = {
    name = "Temple of Ahn'Qiraj",
    category = 3,
    expansion = 0,
    instance = 3,
  },
  [3429] = {
    name = "Ruins of Ahn'Qiraj",
    category = 3,
    expansion = 0,
    instance = 3,
  },
  [3430] = {
    name = "Eversong Woods",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [3433] = {
    name = "Ghostlands",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [3456] = {
    name = "Naxxramas",
    category = 3,
    expansion = 2,
    instance = 7,
  },
  [3457] = {
    name = "Karazhan",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [3483] = {
    name = "Hellfire Peninsula",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3487] = {
    name = "Silvermoon City",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [3518] = {
    name = "Nagrand",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3519] = {
    name = "Terokkar Forest",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3520] = {
    name = "Shadowmoon Valley",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3521] = {
    name = "Zangarmarsh",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3522] = {
    name = "Blade's Edge Mountains",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3523] = {
    name = "Netherstorm",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3524] = {
    name = "Azuremyst Isle",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [3525] = {
    name = "Bloodmyst Isle",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [3537] = {
    name = "Borean Tundra",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [3557] = {
    name = "The Exodar",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [3562] = {
    name = "Hellfire Ramparts",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3606] = {
    name = "Hyjal Summit",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [3607] = {
    name = "Serpentshrine Cavern",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [3703] = {
    name = "Shattrath City",
    category = 8,
    expansion = 1,
    instance = 0,
  },
  [3711] = {
    name = "Sholazar Basin",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [3713] = {
    name = "The Blood Furnace",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3714] = {
    name = "The Shattered Halls",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3715] = {
    name = "The Steamvault",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3716] = {
    name = "The Underbog",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3717] = {
    name = "The Slave Pens",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3789] = {
    name = "Shadow Labyrinth",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3790] = {
    name = "Auchenai Crypts",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3791] = {
    name = "Sethekk Halls",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3792] = {
    name = "Mana-Tombs",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3805] = {
    name = "Zul'Aman",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [3836] = {
    name = "Magtheridon's Lair",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [3845] = {
    name = "The Eye",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [3847] = {
    name = "The Botanica",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3848] = {
    name = "The Arcatraz",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3849] = {
    name = "The Mechanar",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [3923] = {
    name = "Gruul's Lair",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [3959] = {
    name = "Black Temple",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [4075] = {
    name = "Sunwell Plateau",
    category = 3,
    expansion = 1,
    instance = 3,
  },
  [4080] = {
    name = "Isle of Quel'Danas",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [4100] = {
    name = "The Culling of Stratholme",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4131] = {
    name = "Magisters' Terrace",
    category = 2,
    expansion = 1,
    instance = 5,
  },
  [4196] = {
    name = "Drak'Tharon Keep",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4197] = {
    name = "Wintergrasp",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [4228] = {
    name = "The Oculus",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4264] = {
    name = "Halls of Stone",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4265] = {
    name = "The Nexus",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4272] = {
    name = "Halls of Lightning",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4273] = {
    name = "Ulduar",
    category = 3,
    expansion = 2,
    instance = 7,
  },
  [4277] = {
    name = "Azjol-Nerub",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4298] = {
    name = "Plaguelands: The Scarlet Enclave",
    category = 0,
    expansion = 2,
    instance = 0,
  },
  [4395] = {
    name = "Dalaran",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [4415] = {
    name = "The Violet Hold",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4416] = {
    name = "Gundrak",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4493] = {
    name = "The Obsidian Sanctum",
    category = 3,
    expansion = 2,
    instance = 7,
  },
  [4494] = {
    name = "Ahn'kahet: The Old Kingdom",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4500] = {
    name = "The Eye of Eternity",
    category = 3,
    expansion = 2,
    instance = 7,
  },
  [4603] = {
    name = "Vault of Archavon",
    category = 3,
    expansion = 2,
    instance = 7,
  },
  [4706] = {
    name = "Ruins of Gilneas",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [4709] = {
    name = "Southern Barrens",
    category = 1,
    expansion = 0,
    instance = 0,
  },
  [4714] = {
    name = "Gilneas",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [4720] = {
    name = "The Lost Isles",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [4722] = {
    name = "Trial of the Crusader",
    category = 3,
    expansion = 2,
    instance = 8,
  },
  [4723] = {
    name = "Trial of the Champion",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4737] = {
    name = "Kezan",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [4755] = {
    name = "Gilneas City",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [4809] = {
    name = "The Forge of Souls",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4812] = {
    name = "Icecrown Citadel",
    category = 3,
    expansion = 2,
    instance = 8,
  },
  [4813] = {
    name = "Pit of Saron",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4815] = {
    name = "Kelp'thar Forest",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [4820] = {
    name = "Halls of Reflection",
    category = 2,
    expansion = 2,
    instance = 5,
  },
  [4821] = {
    name = "Bilgewater Harbor",
    category = 1,
    expansion = 3,
    instance = 0,
  },
  [4859] = {
    name = "The Frozen Throne",
    category = 10,
    expansion = 2,
    instance = 0,
  },
  [4922] = {
    name = "Twilight Highlands",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [4926] = {
    name = "Blackrock Caverns",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [4945] = {
    name = "Halls of Origination",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [4950] = {
    name = "Grim Batol",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [4987] = {
    name = "The Ruby Sanctum",
    category = 3,
    expansion = 2,
    instance = 8,
  },
  [5004] = {
    name = "Throne of the Tides",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5034] = {
    name = "Uldum",
    category = 1,
    expansion = 3,
    instance = 0,
  },
  [5035] = {
    name = "The Vortex Pinnacle",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5042] = {
    name = "Deepholm",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [5088] = {
    name = "The Stonecore",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5094] = {
    name = "Blackwing Descent",
    category = 3,
    expansion = 3,
    instance = 8,
  },
  [5095] = {
    name = "Tol Barad",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [5144] = {
    name = "Shimmering Expanse",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [5145] = {
    name = "Abyssal Depths",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [5146] = {
    name = "Vashj'ir",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [5166] = {
    name = "Cleft of Shadow",
    category = 1,
    expansion = 3,
    instance = 0,
  },
  [5287] = {
    name = "The Cape of Stranglethorn",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [5334] = {
    name = "The Bastion of Twilight",
    category = 3,
    expansion = 3,
    instance = 8,
  },
  [5339] = {
    name = "Stranglethorn Vale",
    category = 0,
    expansion = 0,
    instance = 0,
  },
  [5351] = {
    name = "Ruins of Gilneas City",
    category = 0,
    expansion = 3,
    instance = 0,
  },
  [5389] = {
    name = "Tol Barad Peninsula",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [5396] = {
    name = "Lost City of the Tol'vir",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5416] = {
    name = "The Maelstrom",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [5600] = {
    name = "Baradin Hold",
    category = 3,
    expansion = 3,
    instance = 7,
  },
  [5638] = {
    name = "Throne of the Four Winds",
    category = 3,
    expansion = 3,
    instance = 8,
  },
  [5695] = {
    name = "Ahn'Qiraj: The Fallen Kingdom",
    category = 1,
    expansion = 3,
    instance = 0,
  },
  [5723] = {
    name = "Firelands",
    category = 3,
    expansion = 3,
    instance = 8,
  },
  [5733] = {
    name = "Molten Front",
    category = 1,
    expansion = 3,
    instance = 0,
  },
  [5736] = {
    name = "The Wandering Isle",
    category = 11,
    expansion = 4,
    instance = 0,
  },
  [5786] = {
    name = "The Nexus",
    category = 2,
    expansion = 3,
    instance = 2,
  },
  [5788] = {
    name = "Well of Eternity",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5789] = {
    name = "End Time",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5844] = {
    name = "Hour of Twilight",
    category = 2,
    expansion = 3,
    instance = 5,
  },
  [5861] = {
    name = "Darkmoon Island",
    category = 11,
    expansion = 3,
    instance = 0,
  },
  [5892] = {
    name = "Dragon Soul",
    category = 3,
    expansion = 3,
    instance = 8,
  },
  [5918] = {
    name = "Shado-Pan Monastery",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [5956] = {
    name = "Temple of the Jade Serpent",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [5963] = {
    name = "Stormstout Brewery",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [5976] = {
    name = "Gate of the Setting Sun",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [6052] = {
    name = "Scarlet Halls",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [6066] = {
    name = "Scholomance",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [6067] = {
    name = "Terrace of Endless Spring",
    category = 3,
    expansion = 4,
    instance = 8,
  },
  [6109] = {
    name = "Scarlet Monastery",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [6125] = {
    name = "Mogu'shan Vaults",
    category = 3,
    expansion = 4,
    instance = 8,
  },
  [6170] = {
    name = "Northshire",
    category = 0,
    expansion = 4,
    instance = 0,
  },
  [6176] = {
    name = "Coldridge Valley",
    category = 0,
    expansion = 4,
    instance = 0,
  },
  [6182] = {
    name = "Mogu'shan Palace",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [6214] = {
    name = "Siege of Niuzao Temple",
    category = 2,
    expansion = 4,
    instance = 5,
  },
  [6297] = {
    name = "Heart of Fear",
    category = 3,
    expansion = 4,
    instance = 8,
  },
  [6384] = {
    name = "Forlorn Cloister",
    category = 2,
    expansion = 4,
    instance = 2,
  },
  [6386] = {
    name = "Chapel Gardens",
    category = 2,
    expansion = 4,
    instance = 2,
  },
  [6450] = {
    name = "Shadowglen",
    category = 1,
    expansion = 4,
    instance = 0,
  },
  [6451] = {
    name = "Valley of Trials",
    category = 1,
    expansion = 4,
    instance = 0,
  },
  [6452] = {
    name = "Camp Narache",
    category = 1,
    expansion = 4,
    instance = 0,
  },
  [6453] = {
    name = "Echo Isles",
    category = 1,
    expansion = 4,
    instance = 0,
  },
  [6454] = {
    name = "Deathknell",
    category = 0,
    expansion = 4,
    instance = 0,
  },
  [6455] = {
    name = "Sunstrider Isle",
    category = 0,
    expansion = 4,
    instance = 0,
  },
  [6456] = {
    name = "Ammen Vale",
    category = 1,
    expansion = 4,
    instance = 0,
  },
  [6457] = {
    name = "New Tinkertown",
    category = 0,
    expansion = 4,
    instance = 0,
  },
  [6622] = {
    name = "Throne of Thunder",
    category = 3,
    expansion = 4,
    instance = 8,
  },
  [6662] = {
    name = "Talador",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6719] = {
    name = "Shadowmoon Valley",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6720] = {
    name = "Frostfire Ridge",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6721] = {
    name = "Gorgrond",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6722] = {
    name = "Spires of Arak",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6723] = {
    name = "Tanaan Jungle",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6738] = {
    name = "Siege of Orgrimmar",
    category = 3,
    expansion = 4,
    instance = 8,
  },
  [6755] = {
    name = "Nagrand",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6756] = {
    name = "Faralohn",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6874] = {
    name = "Bloodmaul Slag Mines",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [6912] = {
    name = "Auchindoun",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [6932] = {
    name = "Shadowmoon Burial Grounds",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [6941] = {
    name = "Ashran",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6951] = {
    name = "Iron Docks",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [6967] = {
    name = "Blackrock Foundry",
    category = 3,
    expansion = 5,
    instance = 7,
  },
  [6980] = {
    name = "Shattrath City",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [6984] = {
    name = "Grimrail Depot",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [6988] = {
    name = "Skyreach",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [6996] = {
    name = "Highmaul",
    category = 3,
    expansion = 5,
    instance = 7,
  },
  [7004] = {
    name = "Frostwall",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [7078] = {
    name = "Lunarfall",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [7083] = {
    name = "Defense of Karabor",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [7109] = {
    name = "The Everbloom",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [7307] = {
    name = "Upper Blackrock Spire",
    category = 2,
    expansion = 5,
    instance = 5,
  },
  [7332] = {
    name = "Stormshield",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [7333] = {
    name = "Warspear",
    category = 13,
    expansion = 5,
    instance = 0,
  },
  [7334] = {
    name = "Azsuna",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7343] = {
    name = "[UNUSED]",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7502] = {
    name = "Dalaran",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7503] = {
    name = "Highmountain",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7541] = {
    name = "Stormheim",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7543] = {
    name = "Broken Shore",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7545] = {
    name = "Hellfire Citadel",
    category = 3,
    expansion = 5,
    instance = 7,
  },
  [7546] = {
    name = "Neltharion's Lair",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7558] = {
    name = "Val'sharah",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7578] = {
    name = "Eye of Azshara",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7634] = {
    name = "Feralas (copy)",
    category = 1,
    expansion = 6,
    instance = 0,
  },
  [7637] = {
    name = "Suramar",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7638] = {
    name = "Sanctum of Light",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7656] = {
    name = "The Great Sea",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7672] = {
    name = "Halls of Valor",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7673] = {
    name = "Darkheart Thicket",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7674] = {
    name = "Legion Dungeon",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7679] = {
    name = "Acherus: The Ebon Hold",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7691] = {
    name = "Small Battleground D",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7731] = {
    name = "Thunder Totem",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7744] = {
    name = "Shield's Rest",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [7745] = {
    name = "The Maelstrom",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7767] = {
    name = "Suramar",
    category = 14,
    expansion = 6,
    instance = 10,
  },
  [7787] = {
    name = "Vault of the Wardens",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7805] = {
    name = "Black Rook Hold",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7811] = {
    name = "The Naglfar",
    category = 2,
    expansion = 6,
    instance = 2,
  },
  [7812] = {
    name = "Maw of Souls",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7813] = {
    name = "Skyhold",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7830] = {
    name = "Helmouth Shallows",
    category = 14,
    expansion = 6,
    instance = 10,
  },
  [7834] = {
    name = "Netherlight Temple",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7846] = {
    name = "The Dreamgrove",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7855] = {
    name = "The Arcway",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [7875] = {
    name = "Dreadscar Rift",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7877] = {
    name = "Trueshot Lodge",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7879] = {
    name = "Hall of the Guardian",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7884] = {
    name = "The Silver Enclave",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7885] = {
    name = "Antonidas Memorial",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7886] = {
    name = "Dalaran City",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7887] = {
    name = "Circle of Wills",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7888] = {
    name = "The Violet Citadel",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7889] = {
    name = "The Violet Citadel Spire",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7890] = {
    name = "Sewer Exit Pipe",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7891] = {
    name = "Sewer Exit Pipe",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7892] = {
    name = "Dalaran Floating Rocks",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7893] = {
    name = "Sunreaver's Sanctuary",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7894] = {
    name = "Dalaran Island",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7895] = {
    name = "The Violet Hold",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7896] = {
    name = "Runeweaver Square",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7897] = {
    name = "The Underbelly",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7898] = {
    name = "The Eventide",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7899] = {
    name = "Magus Commerce Exchange",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7900] = {
    name = "Vargoth's Retreat",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7901] = {
    name = "Violet Citadel Balcony",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7903] = {
    name = "Temple of Five Dawns",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [7921] = {
    name = "Stormheim",
    category = 14,
    expansion = 6,
    instance = 10,
  },
  [7967] = {
    name = "Boost Experience [TEMP NAME]",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [7976] = {
    name = "Tirisfal Glades",
    category = 0,
    expansion = 6,
    instance = 10,
  },
  [7996] = {
    name = "Violet Hold",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [8000] = {
    name = "Azsuna",
    category = 14,
    expansion = 6,
    instance = 10,
  },
  [8005] = {
    name = "Terrace of Endless Spring",
    category = 3,
    expansion = 6,
    instance = 3,
  },
  [8012] = {
    name = "Chamber of Shadows",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [8023] = {
    name = "The Fel Hammer",
    category = 14,
    expansion = 6,
    instance = 11,
  },
  [8025] = {
    name = "The Nighthold",
    category = 3,
    expansion = 6,
    instance = 7,
  },
  [8026] = {
    name = "The Emerald Nightmare",
    category = 3,
    expansion = 6,
    instance = 7,
  },
  [8040] = {
    name = "Eye of Azshara",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [8053] = {
    name = "The Greater Sea (Don't Use)",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8054] = {
    name = "Thal'dranath",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8064] = {
    name = "The MOTHERLODE!!",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [8079] = {
    name = "Court of Stars",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [8091] = {
    name = "Nordrassil",
    category = 1,
    expansion = 6,
    instance = 10,
  },
  [8093] = {
    name = "The Vortex Pinnacle",
    category = 1,
    expansion = 6,
    instance = 0,
  },
  [8124] = {
    name = "Sword of Dawn",
    category = 2,
    expansion = 6,
    instance = 2,
  },
  [8348] = {
    name = "Shal'dorei Terrace",
    category = 3,
    expansion = 6,
    instance = 3,
  },
  [8392] = {
    name = "Dalaran Sewers",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8422] = {
    name = "Tempest's Roar",
    category = 2,
    expansion = 6,
    instance = 2,
  },
  [8440] = {
    name = "Trial of Valor",
    category = 3,
    expansion = 6,
    instance = 7,
  },
  [8443] = {
    name = "Return to Karazhan",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [8445] = {
    name = "The Great Sea",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8449] = {
    name = "xxOLD - Zuldazar City",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [8470] = {
    name = "VictorCortisLand",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [8473] = {
    name = "Dungeon Blockout",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [8474] = {
    name = "Dalaran (Northrend)",
    category = 10,
    expansion = 6,
    instance = 0,
  },
  [8476] = {
    name = "Viperville",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8488] = {
    name = "Underrot",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8489] = {
    name = "Islands",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8499] = {
    name = "Zuldazar",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8500] = {
    name = "Nazmir",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8501] = {
    name = "Vol'dun",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8502] = {
    name = "South Seas",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8524] = {
    name = "Tomb of Sargeras",
    category = 3,
    expansion = 6,
    instance = 7,
  },
  [8525] = {
    name = "Underrot",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8526] = {
    name = "Arathi Basin",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8527] = {
    name = "Cathedral of Eternal Night",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [8529] = {
    name = "Pit of Saron",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [8535] = {
    name = "Dalaran (Deadwind Pass)",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [8566] = {
    name = "The Great Sea",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8567] = {
    name = "Tiragarde Sound",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8568] = {
    name = "Boralus",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8573] = {
    name = "MSandersTest2016",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8574] = {
    name = "Krokuun",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8579] = {
    name = "Isle of Blizzcon",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [8583] = {
    name = "Black Rook Hold",
    category = 2,
    expansion = 6,
    instance = 2,
  },
  [8591] = {
    name = "Shwayder's Tavern",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [8598] = {
    name = "Warden Tower TEMP",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8600] = {
    name = "The Great Sea",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8638] = {
    name = "Antorus, the Burning Throne",
    category = 3,
    expansion = 6,
    instance = 7,
  },
  [8656] = {
    name = "CharacterTestSpaceArea_ECannon",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [8665] = {
    name = "Port of Zandalar",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8666] = {
    name = "Grand Bazaar",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8667] = {
    name = "Tal'farrak",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8668] = {
    name = "Tal'aman",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8670] = {
    name = "Dazar'alor",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8685] = {
    name = "Warsong Gulch",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8700] = {
    name = "The Exodar",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8701] = {
    name = "Eredath",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8712] = {
    name = "The Trial of Style",
    category = 2,
    expansion = 6,
    instance = 2,
  },
  [8714] = {
    name = "The Vindicaar",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8716] = {
    name = "Proudmoore Keep",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8717] = {
    name = "Boralus Harbor",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8718] = {
    name = "Tradewinds Market",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8721] = {
    name = "Drustvar",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8726] = {
    name = "Zanchul",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8729] = {
    name = "The Sliver",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [8801] = {
    name = "Dustwallow Marsh UNUSED",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [8899] = {
    name = "Antoran Wastes",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8910] = {
    name = "The Seat of the Triumvirate",
    category = 2,
    expansion = 6,
    instance = 5,
  },
  [8915] = {
    name = "The Vindicaar",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8916] = {
    name = "The Vindicaar",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [8956] = {
    name = "Gol Thovas",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [8978] = {
    name = "Tol Dagor",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9010] = {
    name = "Shadow of Azeroth",
    category = 0,
    expansion = 6,
    instance = 0,
  },
  [9023] = {
    name = "[Test] Environment Art - Tina 01",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9028] = {
    name = "Atal'Dazar",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9029] = {
    name = "Hozen Island",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9042] = {
    name = "Stormsong Valley",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9101] = {
    name = "Tropical Isle 8.0",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9147] = {
    name = "The Old Seawall",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9164] = {
    name = "Freehold",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9168] = {
    name = "Arathi Highlands",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9172] = {
    name = "Terrace of the Chosen",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9173] = {
    name = "The Zocalo",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9183] = {
    name = "RiverZone_Art",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9310] = {
    name = "Silithus: The Wound",
    category = 1,
    expansion = 6,
    instance = 0,
  },
  [9327] = {
    name = "Tol Dagor",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9331] = {
    name = "Gilneas Island",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9354] = {
    name = "Siege of Boralus",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9355] = {
    name = "Little Tortolla",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9361] = {
    name = "Terrace of the Speakers",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9382] = {
    name = "Sacrificial Pits",
    category = 2,
    expansion = 7,
    instance = 2,
  },
  [9383] = {
    name = "BlizzCon 2017",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9386] = {
    name = "Allied - Highmountain Tauren Unlock",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [9387] = {
    name = "Allied - Lightforged Draenei Unlock",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [9388] = {
    name = "Hero Stage LD Demo Area",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9389] = {
    name = "Uldir",
    category = 3,
    expansion = 7,
    instance = 7,
  },
  [9391] = {
    name = "The Underrot",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9394] = {
    name = "Allied - Orgrimmar",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [9395] = {
    name = "Allied - Stormwind",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [9396] = {
    name = "Allied - Void Elf Unlock",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [9397] = {
    name = "Allied - Nightborne Unlock",
    category = 14,
    expansion = 6,
    instance = 0,
  },
  [9407] = {
    name = "Ashvane Company Yards",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9424] = {
    name = "Waycrest Manor",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9443] = {
    name = "Titan Island",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9467] = {
    name = "White Mesa Isles",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9483] = {
    name = "Katalina Island",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9485] = {
    name = "Wonderland",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9488] = {
    name = "Swamp Island",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9489] = {
    name = "Rock Spire",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9525] = {
    name = "Shrine of the Storm",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9526] = {
    name = "Kings' Rest",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9527] = {
    name = "Temple of Sethraliss",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [9541] = {
    name = "Pandaren Farm Dev",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9552] = {
    name = "Quest Training",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9554] = {
    name = "Stormsong Monastery",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9562] = {
    name = "Thornheart",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9570] = {
    name = "Zuldazar",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9588] = {
    name = "Hook Point",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9593] = {
    name = "Unity Square",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9598] = {
    name = "The Great Seal",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9599] = {
    name = "Spirits Be With You",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9602] = {
    name = "Mariner's Row",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9627] = {
    name = "Crosswind Commons",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9660] = {
    name = "The Drunken Drummer",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9661] = {
    name = "Lost Spirit Lounge",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9662] = {
    name = "Hot House",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9663] = {
    name = "War Campaign - Alliance",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9664] = {
    name = "War Campaign - Horde",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9665] = {
    name = "Atal'Jani",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9669] = {
    name = "South Seas",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9698] = {
    name = "Saltstone Mine",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9703] = {
    name = "Allied - Dark Iron Dwarf Unlock",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9704] = {
    name = "Allied - Mag'har Orc Unlock",
    category = 1,
    expansion = 7,
    instance = 0,
  },
  [9765] = {
    name = "Proudmoore Academy",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9771] = {
    name = "Proudmoore Barracks",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9772] = {
    name = "Rastakhan's Might",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9808] = {
    name = "Eastern Kingdoms",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [9826] = {
    name = "Sword of Dawn",
    category = 2,
    expansion = 7,
    instance = 2,
  },
  [9830] = {
    name = "Tempest's Roar",
    category = 2,
    expansion = 7,
    instance = 2,
  },
  [9962] = {
    name = "Watertusk Inn",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9970] = {
    name = "Hall of Strength",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [9979] = {
    name = "Dampwick Ward",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9980] = {
    name = "Ashvane Docks",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [9994] = {
    name = "Chamber of Rezan",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [10015] = {
    name = "Tol Dagor",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [10028] = {
    name = "Blackrock Depths",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [10034] = {
    name = "Upton Borough",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [10043] = {
    name = "Tol Dagor",
    category = 2,
    expansion = 7,
    instance = 2,
  },
  [10047] = {
    name = "Siege of Orgrimmar",
    category = 3,
    expansion = 7,
    instance = 3,
  },
  [10057] = {
    name = "Crucible of Storms",
    category = 3,
    expansion = 7,
    instance = 7,
  },
  [10076] = {
    name = "Battle of Dazar'alor",
    category = 3,
    expansion = 7,
    instance = 7,
  },
  [10088] = {
    name = "Allied - Zandalari Unlock",
    category = 15,
    expansion = 7,
    instance = 0,
  },
  [10154] = {
    name = "Dragonblight",
    category = 10,
    expansion = 7,
    instance = 0,
  },
  [10155] = {
    name = "Icecrown",
    category = 10,
    expansion = 7,
    instance = 0,
  },
  [10156] = {
    name = "Borean Tundra",
    category = 10,
    expansion = 7,
    instance = 0,
  },
  [10157] = {
    name = "Sholazar Basin",
    category = 10,
    expansion = 7,
    instance = 0,
  },
  [10213] = {
    name = "Nzoth",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [10225] = {
    name = "Operation: Mechagon",
    category = 2,
    expansion = 7,
    instance = 5,
  },
  [10267] = {
    name = "Questfall",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [10290] = {
    name = "Mechagon",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [10380] = {
    name = "Allied - Kul Tiran Unlock",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [10397] = {
    name = "Mulgore",
    category = 1,
    expansion = 7,
    instance = 0,
  },
  [10413] = {
    name = "Revendreth",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [10416] = {
    name = "Siren Isle",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [10425] = {
    name = "The Eternal Palace",
    category = 3,
    expansion = 7,
    instance = 7,
  },
  [10430] = {
    name = "Val'sharah",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [10448] = {
    name = "Darkest Depths",
    category = 3,
    expansion = 7,
    instance = 3,
  },
  [10456] = {
    name = "The Obsidian Sanctum",
    category = 10,
    expansion = 7,
    instance = 0,
  },
  [10522] = {
    name = "Ny'alotha, the Waking City",
    category = 3,
    expansion = 7,
    instance = 7,
  },
  [10534] = {
    name = "Bastion",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [10565] = {
    name = "Oribos",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [10581] = {
    name = "Darkmaul Citadel",
    category = 2,
    expansion = 8,
    instance = 2,
  },
  [10582] = {
    name = "Caverns of Time",
    category = 3,
    expansion = 7,
    instance = 7,
  },
  [10625] = {
    name = "Durotar",
    category = 1,
    expansion = 7,
    instance = 0,
  },
  [10713] = {
    name = "Highmountain",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [10714] = {
    name = "Stormheim",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [10727] = {
    name = "Suramar",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [10731] = {
    name = "The Great Sea",
    category = 14,
    expansion = 7,
    instance = 0,
  },
  [10986] = {
    name = "Sinfall",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [11012] = {
    name = "Elysian Hold",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [11356] = {
    name = "Continent",
    category = 0,
    expansion = 7,
    instance = 0,
  },
  [11382] = {
    name = "8.2.5 War Campaign",
    category = 1,
    expansion = 7,
    instance = 0,
  },
  [11384] = {
    name = "Mogu'shan Palace",
    category = 2,
    expansion = 7,
    instance = 2,
  },
  [11395] = {
    name = "Mogu'shan Vaults",
    category = 3,
    expansion = 7,
    instance = 3,
  },
  [11397] = {
    name = "Temple of the Jade Serpent",
    category = 2,
    expansion = 7,
    instance = 2,
  },
  [11400] = {
    name = "The Maw",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [11510] = {
    name = "Ardenweald",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [11539] = {
    name = "Allied - Mechagnome Unlock",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [11540] = {
    name = "Alllied - Vulpera Unlock",
    category = 16,
    expansion = 7,
    instance = 0,
  },
  [12831] = {
    name = "Halls of Atonement",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [12837] = {
    name = "Spires of Ascension",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [12841] = {
    name = "Theater of Pain",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [12842] = {
    name = "Sanguine Depths",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [12847] = {
    name = "Bastion - Vignettes",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [12848] = {
    name = "Bastion - Treasures",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [12858] = {
    name = "Heart of the Forest",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [12876] = {
    name = "Seat of the Primus",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [12916] = {
    name = "The Necrotic Wake",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [13224] = {
    name = "Castle Nathria",
    category = 3,
    expansion = 8,
    instance = 7,
  },
  [13228] = {
    name = "Plaguefall",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [13309] = {
    name = "De Other Side",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [13329] = {
    name = "The Ember Court",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13332] = {
    name = "The Maw",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13334] = {
    name = "Mists of Tirna Scithe",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [13409] = {
    name = "Progenitor Zone Area 1",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13433] = {
    name = "The In-Between",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13536] = {
    name = "Zereth Mortis",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13548] = {
    name = "Boralus Harbor",
    category = 2,
    expansion = 8,
    instance = 2,
  },
  [13549] = {
    name = "Stormheim",
    category = 2,
    expansion = 8,
    instance = 2,
  },
  [13553] = {
    name = "Escape from the Maw",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13561] = {
    name = "Sanctum of Domination",
    category = 3,
    expansion = 8,
    instance = 7,
  },
  [13570] = {
    name = "Korthia",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13577] = {
    name = "Tazavesh, the Veiled Market",
    category = 2,
    expansion = 8,
    instance = 5,
  },
  [13580] = {
    name = "Fungal Wasteland",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [13581] = {
    name = "Overgrown Canopy",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [13582] = {
    name = "Edge of Darkness",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [13583] = {
    name = "Lug'thun's Crater",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [13633] = {
    name = "9.1 Campaign",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13642] = {
    name = "Dragon Isles",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13643] = {
    name = "The Great Sea",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13644] = {
    name = "The Waking Shores",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13645] = {
    name = "Ohn'ahran Plains",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13646] = {
    name = "The Azure Span",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13647] = {
    name = "Thaldraszus",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13672] = {
    name = "Tazavesh, the Veiled Market",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13708] = {
    name = "Plain of Actualization",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13742] = {
    name = "Sepulcher of the First Ones",
    category = 3,
    expansion = 8,
    instance = 7,
  },
  [13753] = {
    name = "Crypts of the Eternal",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13802] = {
    name = "Tyrhold Reservoir",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13844] = {
    name = "Traitor's Rest",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13862] = {
    name = "Valdrakken",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [13891] = {
    name = "Gravid Repose",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13898] = {
    name = "Catalyst Wards",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13928] = {
    name = "Blooming Foundry",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13952] = {
    name = "Locrian Esper",
    category = 17,
    expansion = 8,
    instance = 0,
  },
  [13954] = {
    name = "The Azure Vault",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [13968] = {
    name = "Uldaman",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [13975] = {
    name = "Tirisfal Glades",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [13982] = {
    name = "The Nokhud Offensive",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [13983] = {
    name = "Tirisfal Glades",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [13991] = {
    name = "Brackenhide Hollow",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [14011] = {
    name = "Neltharus",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [14022] = {
    name = "Zaralek Cavern",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [14030] = {
    name = "Vault of the Incarnates",
    category = 3,
    expansion = 9,
    instance = 7,
  },
  [14032] = {
    name = "Algeth'ar Academy",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [14045] = {
    name = "Tirisfal Glades",
    category = 0,
    expansion = 8,
    instance = 0,
  },
  [14063] = {
    name = "Ruby Life Pools",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [14082] = {
    name = "Halls of Infusion",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [14143] = {
    name = "The Dig",
    category = 2,
    expansion = 9,
    instance = 2,
  },
  [14144] = {
    name = "Hall of the Keepers",
    category = 2,
    expansion = 9,
    instance = 2,
  },
  [14357] = {
    name = "Arathi Highlands",
    category = 0,
    expansion = 9,
    instance = 0,
  },
  [14433] = {
    name = "The Forbidden Reach",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [14514] = {
    name = "Dawn of the Infinite",
    category = 2,
    expansion = 9,
    instance = 5,
  },
  [14529] = {
    name = "Emerald Dream",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [14620] = {
    name = "Blue Dragon Choice",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [14643] = {
    name = "Amirdrassil, the Dream's Hope",
    category = 3,
    expansion = 9,
    instance = 7,
  },
  [14663] = {
    name = "Aberrus, the Shadowed Crucible",
    category = 3,
    expansion = 9,
    instance = 7,
  },
  [14665] = {
    name = "Khaz Algar",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14717] = {
    name = "Isle of Dorn",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14730] = {
    name = "Abandoned Creche",
    category = 0,
    expansion = 10,
    instance = 0,
  },
  [14748] = {
    name = "Khaz Algar",
    category = 0,
    expansion = 10,
    instance = 0,
  },
  [14752] = {
    name = "Azj-Kahet",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14753] = {
    name = "City of Threads",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14765] = {
    name = "Twitching Gorge",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14769] = {
    name = "The Maddening Deep",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14771] = {
    name = "Dornogal",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14776] = {
    name = "The Proscenium",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14795] = {
    name = "The Ringing Deeps",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14838] = {
    name = "Hallowfall",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [14842] = {
    name = "Ulderoth",
    category = 2,
    expansion = 9,
    instance = 2,
  },
  [14872] = {
    name = "Scarlet Monastery",
    category = 2,
    expansion = 9,
    instance = 2,
  },
  [14882] = {
    name = "Darkflame Cleft",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [14883] = {
    name = "The Stonevault",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [14938] = {
    name = "The Rookery",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [14954] = {
    name = "Priory of the Sacred Flame",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [14971] = {
    name = "The Dawnbreaker",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [14979] = {
    name = "City of Threads",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [14980] = {
    name = "Nerub-ar Palace",
    category = 3,
    expansion = 10,
    instance = 7,
  },
  [15093] = {
    name = "Ara-Kara, City of Echoes",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [15103] = {
    name = "Cinderbrew Meadery",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [15105] = {
    name = "Amirdrassil",
    category = 18,
    expansion = 9,
    instance = 0,
  },
  [15336] = {
    name = "K'aresh",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [15347] = {
    name = "Undermine",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [15452] = {
    name = "Operation: Floodgate",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [15522] = {
    name = "Liberation of Undermine",
    category = 3,
    expansion = 10,
    instance = 7,
  },
  [15525] = {
    name = "The Great Sea",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [15667] = {
    name = "Delves",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [15781] = {
    name = "Tazavesh, the Veiled Market",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [15827] = {
    name = "The Forgotten Vault",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [15913] = {
    name = "Blackrock Depths",
    category = 3,
    expansion = 10,
    instance = 3,
  },
  [16092] = {
    name = "Dastardly Duos",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [16093] = {
    name = "Undermine",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [16104] = {
    name = "Eco-Dome Al'dani",
    category = 2,
    expansion = 10,
    instance = 5,
  },
  [16108] = {
    name = "The Great Sea",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [16178] = {
    name = "Manaforge Omega",
    category = 3,
    expansion = 10,
    instance = 7,
  },
  [16309] = {
    name = "Castle Nathria",
    category = 0,
    expansion = 10,
    instance = 0,
  },
  [16505] = {
    name = "Voidscar Cavern",
    category = 19,
    expansion = 10,
    instance = 0,
  },
  [16571] = {
    name = "Wastes of K'aresh",
    category = 3,
    expansion = 10,
    instance = 3,
  },
  [16572] = {
    name = "The Glassed Expanse",
    category = 3,
    expansion = 10,
    instance = 3,
  },
  [16579] = {
    name = "K'aresh",
    category = 19,
    expansion = 10,
    instance = 0,
  },
}

-- Location lookup by name (case-insensitive)
LocationData.byName = {}
for id, data in pairs(LocationData.byId) do
  local nameLower = data.name:lower()
  LocationData.byName[nameLower] = data
end

-- Lookup location by name
function LocationData:Find(name)
  if not name then return nil end
  local nameLower = name:lower()
  return self.byName[nameLower]
end

-- Get location type for context phrase selection
function LocationData:GetLocationType(name)
  local data = self:Find(name)
  if not data then return 'zone' end
  
  if data.category == 2 then return 'dungeon' end
  if data.category == 3 then return 'raid' end
  
  -- Zone type
  return 'zone'
end

-- Total locations: 603
-- Locations by category:
--   Eastern Kingdoms: 116
--   Kalimdor: 46
--   Dungeon: 153
--   Raid: 63
--   Outland: 8
--   Northrend: 18
--   Cataclysm Zone: 8
--   Draenor: 15
--   Broken Isles: 54
--   Kul Tiras: 30
--   Zandalar: 30
--   Shadowlands: 26
--   Dragon Isles: 14
--   Khaz Algar: 22
